# action.yml
name: 'SyncRepositories'
description: 'Allow syncing some files or dirs between repositories'
inputs:
  config-path:
    description: 'Path to action configuration'
    required: true
    default: '.syncconfig'
  token:
    description: 'GitHub Token to get access to repository'
    required: true
  email:
    description: 'Author of commit (email)'
    required: true
  commit-message:
    description: 'Message for commit'
    required: true
    default: "Sync"
  pr-title:
    description: 'Title for pull request'
    required: false
  pr-body:
    description: 'Body for pull request'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config-path }}
    - ${{ inputs.token }}
    - ${{ inputs.email }}
    - ${{ inputs.commit-message }}
    - ${{ inputs.pr-title }}
    - ${{ inputs.pr-body }}
