on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync Repositories
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Syncing
        inputs:
          token: ${{ secrets.TOKEN }}
          pr-title: 'Syncing PR'
          email: 'likdan.official@gmail.com'
        uses: ./

